name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      uses: robherley/go-test-action@v0.1.0
      with:
        testArguments: './... -coverprofile=./cover.out -covermode=atomic -coverpkg=./... > test.json'

    - name: Check coverage
      uses: vladopajic/go-test-coverage@v2
      if: always()
      with:
        profile: cover.out
        threshold-file: 80
        threshold-package: 80
        threshold-total: 95

    - name: Annotate tests
      if: always()
      uses: guyarb/golang-test-annotations@v0.7.0
      with:
        test-results: /test.json
        package-name: goghactionspoc
